In [1]:
import numpy as np

In [2]:
# 예시 데이터 생성
x =np.array([1,2,3,4,5]) # 변수 x의 값
y =np.array([2,4,6,8,10]) # 변수 y의 값
z =np.array([3,6,9,12,15]) # 변수 z의 값

# 공분산 계산
cov_matrix = np.cov([x,y,z])
print("Covariance Matrix")
print(cov_matrix)

# 상관 행렬 계산
cov_matrix = np.corrcoef([x,y,z])
print("\nCorrelation Matrix:")
print(cov_matrix)

Covariance Matrix
[[ 2.5  5.   7.5]
 [ 5.  10.  15. ]
 [ 7.5 15.  22.5]]

Correlation Matrix:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# 예시 데이터 생성
x1 =np.array([1,2,3,4,5]) # 변수 x1의 값
x2 =np.array([2,4,6,8,10]) # 변수 x2의 값
x3 =np.array([3,6,9,12,15]) # 변수 x3의 값

# 데이터 행렬 생성 
data = np.vstack([x1,x2,x3]).T

# 상관 행렬 계산 
cor_matrix = np.corrcoef(data,rowvar=False)

# 각 변수들 간의 상관 계수 출력
print("Correlation Coefficients:")
print(cor_matrix)

# 다중 공선성 판단
threshold = 0.7 #상관 계수의 임계값 설정

print("\nVariables with high multicollinearity")
for i in range(cor_matrix.shape[0]):
    for j in range(i+1, cor_matrix.shape[1]):
        if abs(cor_matrix[i,j])>threshold:
            print(f"Varialble {i+1} and Variable {j+1}")

Correlation Coefficients:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Variables with high multicollinearity
Varialble 1 and Variable 2
Varialble 1 and Variable 3
Varialble 2 and Variable 3
