In [5]:
import numpy as np
from sklearn.decomposition import FactorAnalysis

In [6]:
# 데이터셋 생성
np.random.seed(0)
n_samples = 100 # 샘플 수 
n_features = 5 # 변수 수
 
# 데이터셋을 랜덤하게 생성 
X = np.random.randn(n_samples, n_features)

In [8]:
# 인자 분석 수행
n_components = 2 # 추출할 인자 수
factor_anlaysis = FactorAnalysis(n_components=n_components, random_state=0)
X_factors = factor_anlaysis.fit_transform(X)

In [9]:
# 결과 출력
print("원본 데이터셋 크기: ", X.shape)
print("인자 분석 결과 (인자 개수={}):".format(n_components))
print(X_factors)

원본 데이터셋 크기:  (100, 5)
인자 분석 결과 (인자 개수=2):
[[-1.01244523e+00 -1.30255487e-01]
 [-4.66728317e-01  1.13128805e-01]
 [-5.43752664e-01 -5.21333643e-03]
 [ 7.84485254e-02  5.18446209e-01]
 [-1.38761949e+00 -7.19926702e-01]
 [-9.76908725e-01 -1.46287371e-01]
 [ 4.16681019e-01  4.39943804e-01]
 [-9.33912119e-02 -2.05477909e-01]
 [ 3.64050421e-01  3.62622003e-01]
 [ 6.01596203e-01 -6.83470132e-01]
 [ 3.50941854e-02  1.47999277e-01]
 [ 3.27489939e-01 -4.67195360e-02]
 [ 2.35314537e-01  1.14712133e-01]
 [ 5.05245409e-01 -6.23279966e-01]
 [ 3.59883386e-02 -4.08163985e-01]
 [ 2.39779405e-01 -4.48204528e-02]
 [-8.19922431e-01 -2.90047066e-01]
 [-3.74929007e-01  4.89847246e-01]
 [-5.91241735e-01  1.33901943e-01]
 [-1.25865487e-01 -6.65994076e-01]
 [ 1.09189763e+00  5.99643113e-01]
 [-5.03067494e-01  4.54821044e-01]
 [-3.78276132e-02  8.83335518e-01]
 [-5.86593018e-01  3.42129299e-01]
 [ 5.34799613e-01 -2.23164331e-01]
 [-1.80718542e-01 -8.86797699e-01]
 [ 1.48310037e-01  3.39796716e-01]
 [ 4.54069218

In [16]:
from sklearn.datasets import make_blobs
from sklearn.cluster import KMeans

In [17]:
# 데이터 랜덤 생성 
x,y = make_blobs(n_samples=100, centers=4, random_state=42)

#K-means 알고리즘 적용
kmeans =KMeans(n_clusters=4, random_state=42)
kmeans.fit(X)

C:\Users\noeyx\anaconda3\envs\AI\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


KMeans(n_clusters=4, random_state=42)

In [18]:
# 군집 중심점 확인 
centroids = kmeans.cluster_centers_
print("군집 중심점:")
print(centroids)

# 군집 예측 결과 확인
labels= kmeans.labels_
print("군집 예측 결과:")
print(labels)

#결과 해석
for i in range(len(centroids)):
    cluster_data= X[labels==i] # 해당 군집에 속하는 데이터
    cluster_center = centroids[i] # 해당 군집의 중심점
    

군집 중심점:
[[ 0.27587516  0.03157909 -1.05003398 -0.78549854  0.01419684]
 [ 0.34679158  0.51686201 -0.32133235  1.29385375  0.43319955]
 [-1.47023439  0.43495823  0.11537175 -0.26427949  1.29649036]
 [-0.05009849 -0.47132919  0.64585886 -0.24058663 -0.33681994]]
군집 예측 결과:
[1 2 1 1 2 2 0 3 1 3 0 3 0 3 3 0 2 0 1 3 0 1 1 1 3 3 0 1 2 3 0 0 3 1 3 0 0
 2 2 1 3 2 3 1 3 3 3 1 3 3 3 0 3 3 3 2 1 3 3 3 2 0 0 0 3 3 3 3 0 3 3 3 3 3
 3 0 0 1 0 1 3 3 2 1 0 0 3 1 3 0 2 0 3 0 2 1 0 2 2 0]
